version: 2.1
orbs:
  snyk: snyk/snyk@0.0.10
jobs:
  build:
    docker:
      - image: 'circleci/node:4.8.2'
    steps:
      - checkout
      - run: npm install -q
      - snyk/scan
        severity-threshold: high
        token-variable: SNYK_TOKEN
    
